- name: Make sure that nvim directory exists
  file:
    path: ~/.config/nvim
    state: directory

- name: Make sure that nvim config directory exists
  file:
    path: ~/.config/nvim/config
    state: directory

- name: Make sure that nvim plug directory exists
  file:
    path: ~/.config/nvim/plug
    state: directory

- name: Copy init.vim
  copy:
    src: files/nvim/init.vim
    dest: ~/.config/nvim/init.vim

- name: Copy plug
  copy:
    src: files/nvim/plug/base.vim
    dest: ~/.config/nvim/plug/base.vim

- name: Copy config
  synchronize:
    src: files/nvim/config/base/
    dest: ~/.config/nvim/config/base/
    delete: yes

- name: Install plugins
  command: nvim +PlugInstall +UpdateRemotePlugins +qall

- name: Promptline
  command: nvim "+PromptlineSnapshot! ~/.config/zsh/prompt.sh lightline" +qall
