- name: Clone antigen
  git:
    repo: https://github.com/zsh-users/antigen
    dest: ~/.config/zsh/antigen/

- name: Copy zshrc
  copy:
    src: files/zsh/.zshrc
    dest: ~/.zshrc

- name: Copy config
  copy:
    src: files/zsh/config/base.zsh
    dest: ~/.config/zsh/config/base.zsh
