Plug 'Shougo/deoplete.nvim'
Plug 'Shougo/neosnippet'
Plug 'Shougo/neosnippet-snippets'
Plug 'Shougo/neoinclude.vim'
Plug 'tpope/vim-fugitive'
Plug 'benekastah/neomake'
Plug 'airblade/vim-gitgutter'

" Language specific
Plug 'digitaltoad/vim-jade'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'marijnh/tern_for_vim'
Plug 'mustache/vim-mustache-handlebars'
Plug 'Rip-Rip/clang_complete'
Plug 'zchee/deoplete-jedi'
Plug 'sheerun/vim-polyglot'
Plug 'benjie/neomake-local-eslint.vim'
