- name: "create nathanajah user"
  user:
    name: nathanajah
    state: present

- name: Allow nathanajah to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%nathanajah'
    line: 'nathanajah ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add authorized keys
  ansible.posix.authorized_key:
    user: nathanajah
    state: present
    key: https://github.com/nathanajah.keys
