- name: Make sure that nvim runtime plug directory exists
  file:
    path: ~/.config/nvim/plug/archlaptop/
    state: directory

- name: Make sure that nvim runtime config directory exists
  file:
    path: ~/.config/nvim/config/archlaptop/
    state: directory

- name: Copy plug
  synchronize:
    src: files/nvim/plug/
    dest: ~/.config/nvim/plug/runtime/archlaptop/
    delete: yes

- name: Copy config
  synchronize:
    src: files/nvim/config/
    dest: ~/.config/nvim/config/runtime/archlaptop/
    delete: yes

- name: Install plugins
  command: nvim +PlugInstall +qall

- name: Promptline
  command: nvim "+PromptlineSnapshot! ~/.config/zsh/prompt.sh lightline" +qall
