- name: "install git - mac"
  homebrew:
    name: git
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "install git - archlinux"
  pacman:
    name: git
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install git - ubuntu"
  apt:
    name: git
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "install delta - mac"
  homebrew:
    name: git-delta
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "Install delta - ubuntu"
  apt:
    name: git-delta
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "Install delta - archlinux"
  pacman:
    name: git-delta
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "Install lazygit - mac"
  homebrew:
    name: jesseduffield/lazygit/lazygit
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "Install lazygit - archlinux"
  pacman:
    name: lazygit
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "Install lazygit - ubuntu"
  apt:
    name: lazygit
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
