- name: "add nvim tap - mac"
  homebrew_tap:
    name: neovim/neovim
    state: present
  when: ansible_distribution == 'MacOSX'

- name: "install nvim - mac"
  homebrew:
    name: neovim
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "install nvim - archlinux"
  pacman:
    name: neovim
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "add nvim ppa - ubuntu"
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"
    state: "present"
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "install nvim - ubuntu"
  apt:
    name: neovim
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
