- name: "install python3 - mac"
  homebrew:
    name: python3
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "install python3 - archlinux"
  pacman:
    name: python
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install pip3 - archlinux"
  pacman:
    name: python-pip
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install python3 - ubuntu"
  apt:
    name: python3
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "install python3-venv - ubuntu"
  apt:
    name: python3-venv
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "install pip3 - ubuntu"
  apt:
    name: python3-pip
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
