- name: "clone rbenv"
  git:
    dest: ~/.rbenv
    repo: https://github.com/rbenv/rbenv.git

- name: "make sure rbenv plugin folder exists"
  file:
    path: ~/.rbenv/plugins
    state: directory

- name: "clone ruby-build"
  git:
    dest: ~/.rbenv/plugins/ruby-build
    repo: https://github.com/rbenv/ruby-build.git

- name: Check that ruby 2.6.0 exists
  stat:
    path: ~/.rbenv/versions/2.6.0
  register: rbenv_2_6_0

- name: Install requirements for ubuntu
  apt:
    name:
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "install ruby 2.6.0"
  shell: ~/.rbenv/bin/rbenv install 2.6.0
  when: rbenv_2_6_0.stat.exists == False

- name: "use ruby 2.6.0"
  shell: ~/.rbenv/bin/rbenv global 2.6.0
