- name: "Install ruby - mac"
  homebrew:
    name: ruby
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "Install ruby - archlinux"
  pacman:
    name: ruby
    state: latest
  become: true
  when: ansible_distribution == 'Arch Linux'

- name: "Install ruby - ubuntu"
  apt:
    name: ruby
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: "Install ruby-dev - ubuntu"
  apt:
    name: ruby-dev
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
