- name: "clone rbenv"
  git:
    dest: ~/.rbenv
    repo: https://github.com/rbenv/rbenv.git

- name: "make sure rbenv plugin folder exists"
  file:
    path: ~/.rbenv/plugins
    state: directory

- name: "clone ruby-build"
  git:
    dest: ~/.rbenv/plugins/ruby-build
    repo: https://github.com/rbenv/ruby-build.git

- name: Check that ruby 2.5.1 exists
  stat:
    path: ~/.rbenv/versions/2.5.1
  register: rbenv_2_5_1

- name: Install ssl requirements for ubuntu
  apt:
    name: libssl-dev
    state: latest
- name: Install readline requirements for ubuntu
  apt:
    name: libreadline-dev
    state: latest
- name: Install zlib1g requirements for ubuntu
  apt:
    name: zlib1g-dev
    state: latest

- name: "install ruby 2.5.1"
  shell: ~/.rbenv/bin/rbenv install 2.5.1
  when: rbenv_2_5_1.stat.exists == False

- name: "use ruby 2.5.1"
  shell: ~/.rbenv/bin/rbenv global 2.5.1
