- name: "install tmux - mac"
  homebrew:
    name: tmux
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "install tmux - archlinux"
  pacman:
    name: tmux
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install tmux - ubuntu"
  apt:
    name: tmux
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
