- name: "install ctags - mac"
  homebrew:
    name: ctags
    state: latest
  become: true
  when: ansible_distribution == 'MacOSX'

- name: "install ctags - archlinux"
  pacman:
    name: ctags
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install ctags - ubuntu"
  apt:
    name: exuberant-ctags
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
