- name: "install python3-neovim"
  pip:
    name: neovim
    state: latest
    executable: pip3
  become: true

- name: "install python2-neovim"
  pip:
    name: neovim
    state: latest
    executable: pip2
  become: true
