- name: "install ranger - archlinux"
  pacman:
    name: ranger
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'

- name: "install ranger - ubuntu"
  apt:
    name: ranger
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
