- name: "install zsh - mac"
  homebrew:
    name: zsh
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "install zsh - archlinux"
  pacman:
    name: zsh
    state: latest
  become: true
  when: ansible_distribution == 'Arch Linux'

- name: "install zsh - ubuntu"
  apt:
    name: zsh
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
  
