- name: "Install haskell-stack - mac"
  homebrew:
    name: haskell-stack
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: "Install haskell-stack - ubuntu"
  apt:
    name: haskell-stack
    state: latest
  become: true
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: "Install haskell-stack - archlinux"
  pacman:
    name: stack
    state: latest
  become: true
  when: ansible_distribution == 'Archlinux'
