- name: Make sure that nvim runtime plug directory exists
  file:
    path: ~/.config/nvim/plug/runtime/
    state: directory

- name: Make sure that nvim runtime config directory exists
  file:
    path: ~/.config/nvim/config/runtime/
    state: directory

- name: Copy plug
  synchronize:
    src: files/nvim/plug/
    dest: ~/.config/nvim/plug/runtime/dev/
    delete: yes

- name: Copy config
  synchronize:
    src: files/nvim/config/
    dest: ~/.config/nvim/config/runtime/dev/
    delete: yes

- name: Install plugins
  command: nvim +PlugInstall +qall
